### ISSUE TITLE
Default model requires token?

### ISSUE THREAD

**Issue by yourbartender** [brycedrennan/imaginAIry#155]
I can use custom models downloaded on my computer, but out of the box 7.3.0 gives me an error: 

TypeError: hf_hub_download() got an unexpected keyword argument 'token'

**Comment by brycedrennan** [comment]
Did you install via pip because this error looks related to changes I just made but haven't released yet.

**Comment by brycedrennan** [comment]
real bug though. Can you run `pip show huggingface-hub` and share the output?

**Comment by brycedrennan** [comment]
You should be able to install a working version by just running `pip install imaginairy`

**Comment by yourbartender** [comment]
~ % pip3 show huggingface-hub 

Name: huggingface-hub
Version: 0.9.1
Summary: Client library to download and publish models, datasets and other repos on the huggingface.co hub
Home-page: https://github.com/huggingface/huggingface_hub
Author: Hugging Face, Inc.
Author-email: julien@huggingface.co
License: Apache
Location: /opt/homebrew/lib/python3.10/site-packages
Requires: filelock, packaging, pyyaml, requests, tqdm, typing-extensions
Required-by: diffusers, open-clip-torch, transformers

**Comment by yourbartender** [comment]
I'm installing locally with pip -e mainly because I've made modifications to cmds, some shortcuts such as -s for steps etc. and I have created a UI which stores and uses these shortcuts. Also some modifications to the way the file is named so the arguiments and the imagine string are easier to split apart later on (in the UI)

**Comment by brycedrennan** [comment]
I think I fixed this in just-realeased 7.4.1. let me know if it's still broken please

**Comment by yourbartender** [comment]
Doesn't work in 7.4.3. Tried a customised version as well as out of the box downloaded version 
`Downloading https://huggingface.co/runwayml/stable-diffusion-v1-5/resolve/889b629140e71758e1e0006e355c331a5744b4bf/v1-5-pruned-emaonly.ckpt from huggingface
Traceback (most recent call last):
  File "/opt/homebrew/bin/imagine", line 33, in <module>
    sys.exit(load_entry_point('imaginAIry', 'console_scripts', 'imagine')())
  File "/opt/homebrew/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/opt/homebrew/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/opt/homebrew/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/homebrew/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/opt/homebrew/lib/python3.10/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/tknuutil/AIstuff/imaginAIry-master/imaginairy/cmds.py", line 317, in imagine_cmd
    imagine_image_files(
  File "/Users/tknuutil/AIstuff/imaginAIry-master/imaginairy/api.py", line 76, in imagine_image_files
    for result in imagine(
  File "/Users/tknuutil/AIstuff/imaginAIry-master/imaginairy/api.py", line 135, in imagine
    model = get_diffusion_model(
  File "/Users/tknuutil/AIstuff/imaginAIry-master/imaginairy/model_manager.py", line 138, in get_diffusion_model
    return _get_diffusion_model(
  File "/Users/tknuutil/AIstuff/imaginAIry-master/imaginairy/model_manager.py", line 196, in _get_diffusion_model
    model.num_timesteps_cond  # noqa
  File "/Users/tknuutil/AIstuff/imaginAIry-master/imaginairy/model_manager.py", line 59, in __getattr__
    model = load_model_from_config(
  File "/Users/tknuutil/AIstuff/imaginAIry-master/imaginairy/model_manager.py", line 86, in load_model_from_config
    ckpt_path = get_cached_url_path(weights_location, category="weights")
  File "/Users/tknuutil/AIstuff/imaginAIry-master/imaginairy/model_manager.py", line 274, in get_cached_url_path
    return huggingface_cached_path(url)
  File "/Users/tknuutil/AIstuff/imaginAIry-master/imaginairy/model_manager.py", line 334, in huggingface_cached_path
    dest_path = hf_hub_download(
  File "/Users/tknuutil/AIstuff/imaginAIry-master/imaginairy/model_manager.py", line 321, in hf_hub_download
    return _hf_hub_download(*args, **kwargs)
TypeError: hf_hub_download() got an unexpected keyword argument 'token'`

**Comment by yourbartender** [comment]
also models available in the help fail, e.g. imagine --model SD-2.1 "testing"

**Comment by yourbartender** [comment]
Edit: now also fails with custom models
FileNotFoundError: [Errno 2] No such file or directory: '/Users/tknuutil/AIstuff/imaginAIry-master/imaginairy/None

**Comment by yourbartender** [comment]
tried reinstalling rust and setuptools, and more (different) errors occur

  File "/opt/homebrew/lib/python3.10/site-packages/pkg_resources/__init__.py", line 617, in _build_master
    ws.require(__requires__)
  File "/opt/homebrew/lib/python3.10/site-packages/pkg_resources/__init__.py", line 956, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/opt/homebrew/lib/python3.10/site-packages/pkg_resources/__init__.py", line 815, in resolve
    dist = self._resolve_dist(
  File "/opt/homebrew/lib/python3.10/site-packages/pkg_resources/__init__.py", line 861, in _resolve_dist
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (setuptools 66.0.0 (/opt/homebrew/lib/python3.10/site-packages), Requirement.parse('setuptools<60'), {'numba'})

**Comment by yourbartender** [comment]
reverting back to 7.2.0 sovels the issue for me (but leaves out all the fun new features :)

**Comment by brycedrennan** [comment]
Please try a vanilla install and see if the issue persists: `pip uninstall imaginairy && pip install imaginairy ---upgrade`

**Comment by brycedrennan** [comment]
Need to rule out that it's the modifications you made

**Comment by yourbartender** [comment]
this one at least starts to load the model… my modifications have been quite small but I guess there was something that got upset the thing. I'll come back to this if after downloading the model it fails

**Comment by yourbartender** [comment]
The default model works, but custom models don't anymore

**Comment by yourbartender** [comment]
Traceback (most recent call last):
  File "/opt/homebrew/bin/imagine", line 8, in <module>
    sys.exit(imagine_cmd())
  File "/opt/homebrew/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/opt/homebrew/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/opt/homebrew/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/homebrew/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/opt/homebrew/lib/python3.10/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/opt/homebrew/lib/python3.10/site-packages/imaginairy/cmds.py", line 304, in imagine_cmd
    imagine_image_files(
  File "/opt/homebrew/lib/python3.10/site-packages/imaginairy/api.py", line 76, in imagine_image_files
    for result in imagine(
  File "/opt/homebrew/lib/python3.10/site-packages/imaginairy/api.py", line 135, in imagine
    model = get_diffusion_model(
  File "/opt/homebrew/lib/python3.10/site-packages/imaginairy/model_manager.py", line 138, in get_diffusion_model
    return _get_diffusion_model(
  File "/opt/homebrew/lib/python3.10/site-packages/imaginairy/model_manager.py", line 196, in _get_diffusion_model
    model.num_timesteps_cond  # noqa
  File "/opt/homebrew/lib/python3.10/site-packages/imaginairy/model_manager.py", line 54, in __getattr__
    model_config = OmegaConf.load(f"{PKG_ROOT}/{self._config_path}")
  File "/opt/homebrew/lib/python3.10/site-packages/omegaconf/omegaconf.py", line 183, in load
    with io.open(os.path.abspath(file_), "r", encoding="utf-8") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/homebrew/lib/python3.10/site-packages/imaginairy/None'

**Comment by brycedrennan** [comment]
Confirmed bug

**Comment by brycedrennan** [comment]
fix on the way

**Comment by federicotorrielli** [comment]
I have a similar bug, on Linux, Pop_OS @brycedrennan :
```
Downloading https://huggingface.co/runwayml/stable-diffusion-v1-5/resolve/889b629140e71758e1e0006e355c331a5744b4bf/v1-5-pruned-emaonly.ckpt from huggingface
Traceback (most recent call last):
  File "/home/evilscript/.local/bin/imagine", line 8, in <module>
    sys.exit(imagine_cmd())
  File "/usr/lib/python3/dist-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/evilscript/.local/lib/python3.10/site-packages/imaginairy/cmds.py", line 265, in imagine_cmd
    return _imagine_cmd(
  File "/home/evilscript/.local/lib/python3.10/site-packages/imaginairy/cmds.py", line 701, in _imagine_cmd
    imagine_image_files(
  File "/home/evilscript/.local/lib/python3.10/site-packages/imaginairy/api.py", line 84, in imagine_image_files
    for result in imagine(
  File "/home/evilscript/.local/lib/python3.10/site-packages/imaginairy/api.py", line 159, in imagine
    model = get_diffusion_model(
  File "/home/evilscript/.local/lib/python3.10/site-packages/imaginairy/model_manager.py", line 145, in get_diffusion_model
    return _get_diffusion_model(
  File "/home/evilscript/.local/lib/python3.10/site-packages/imaginairy/model_manager.py", line 203, in _get_diffusion_model
    model.num_timesteps_cond  # noqa
  File "/home/evilscript/.local/lib/python3.10/site-packages/imaginairy/model_manager.py", line 60, in __getattr__
    model = load_model_from_config(
  File "/home/evilscript/.local/lib/python3.10/site-packages/imaginairy/model_manager.py", line 95, in load_model_from_config
    ckpt_path = get_cached_url_path(weights_location, category="weights")
  File "/home/evilscript/.local/lib/python3.10/site-packages/imaginairy/model_manager.py", line 284, in get_cached_url_path
    return huggingface_cached_path(url)
  File "/home/evilscript/.local/lib/python3.10/site-packages/imaginairy/model_manager.py", line 344, in huggingface_cached_path
    dest_path = hf_hub_download(
  File "/home/evilscript/.local/lib/python3.10/site-packages/imaginairy/model_manager.py", line 331, in hf_hub_download
    return _hf_hub_download(*args, **kwargs)
TypeError: hf_hub_download() got an unexpected keyword argument 'token'
```

**Comment by brycedrennan** [comment]
@federicotorrielli can you tell what version of `huggingface_hub` you have installed so I can debug further? probably fixed by just updating to a newer version of huggingface_hub

**Comment by federicotorrielli** [comment]
> @federicotorrielli can you tell what version of `huggingface_hub` you have installed so I can debug further? probably fixed by just updating to a newer version of huggingface_hub

Doing `pip install -U --force-reinstall imaginairy` fixed everything, tell the others!

**Comment by brycedrennan** [comment]
Great good to know - thanks
